"""add transcripts and summaries

Revision ID: 30ade5c26128
Revises: a6c95aed96ba
Create Date: 2025-12-25 22:27:45.272491

"""
from alembic import op
import sqlalchemy as sa



revision = '30ade5c26128'
down_revision = 'a6c95aed96ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summaries_active', 'summaries', ['task_id', 'summary_type'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_summaries_task', 'summaries', ['task_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('speaker_id', sa.String(length=50), nullable=True),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('end_time', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcripts_fts', 'transcripts', [sa.literal_column("to_tsvector('simple', content)")], unique=False, postgresql_using='gin')
    op.create_index('idx_transcripts_sequence', 'transcripts', ['task_id', 'sequence'], unique=False)
    op.create_index('idx_transcripts_speaker', 'transcripts', ['task_id', 'speaker_id'], unique=False)
    op.create_index('idx_transcripts_task', 'transcripts', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcripts_task', table_name='transcripts')
    op.drop_index('idx_transcripts_speaker', table_name='transcripts')
    op.drop_index('idx_transcripts_sequence', table_name='transcripts')
    op.drop_index('idx_transcripts_fts', table_name='transcripts', postgresql_using='gin')
    op.drop_table('transcripts')
    op.drop_index('idx_summaries_task', table_name='summaries')
    op.drop_index('idx_summaries_active', table_name='summaries', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('summaries')
    # ### end Alembic commands ###
