"""add_task_stages_table

Revision ID: 6df3a190cdf6
Revises: b0fa397f93b6
Create Date: 2026-01-01 02:07:41.931111

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '6df3a190cdf6'
down_revision = 'b0fa397f93b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_stages',
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stage_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('stage_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_stages_status', 'task_stages', ['status'], unique=False)
    op.create_index('idx_task_stages_task', 'task_stages', ['task_id'], unique=False)
    op.create_index('idx_task_stages_unique_active', 'task_stages', ['task_id', 'stage_type'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_stages_unique_active', table_name='task_stages', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_task_stages_task', table_name='task_stages')
    op.drop_index('idx_task_stages_status', table_name='task_stages')
    op.drop_table('task_stages')
    # ### end Alembic commands ###
