"""init

Revision ID: a6c95aed96ba
Revises: 
Create Date: 2025-12-25 00:14:18.547777

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'a6c95aed96ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'deleted_at', name='uk_users_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_phone', 'users', ['phone'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND phone IS NOT NULL'))
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_key', sa.Text(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('asr_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', 'deleted_at', name='uk_tasks_hash')
    )
    op.create_index('idx_tasks_created', 'tasks', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_tasks_hash', 'tasks', ['content_hash'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_tasks_user', 'tasks', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_user', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_tasks_status', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_tasks_hash', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_tasks_created', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_phone', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND phone IS NOT NULL'))
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
