"""add notifications table with improved schema

Revision ID: b0fa397f93b6
Revises: 644f83942f7b
Create Date: 2026-01-01 00:18:47.737758

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'b0fa397f93b6'
down_revision = '644f83942f7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_category', 'notifications', ['user_id', 'category', 'created_at'], unique=False)
    op.create_index('ix_notifications_cleanup', 'notifications', ['read_at', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NOT NULL'))
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL AND dismissed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL AND dismissed_at IS NULL'))
    op.drop_index('ix_notifications_cleanup', table_name='notifications', postgresql_where=sa.text('read_at IS NOT NULL'))
    op.drop_index('ix_notifications_category', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
