"""Add comparison_id to summaries table

Revision ID: f95331911f51
Revises: 6df3a190cdf6
Create Date: 2026-01-02 16:34:41.493602

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'f95331911f51'
down_revision = '6df3a190cdf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_accounts_user")
    op.execute("DROP TABLE IF EXISTS accounts")
    op.add_column('summaries', sa.Column('comparison_id', sa.String(length=50), nullable=True))
    op.execute("DROP INDEX IF EXISTS ix_summaries_task_type")
    op.execute("DROP INDEX IF EXISTS ix_tasks_created_at")
    op.execute("DROP INDEX IF EXISTS ix_tasks_user_status_created")
    op.execute("DROP INDEX IF EXISTS ix_transcripts_task_sequence")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transcripts_task_sequence'), 'transcripts', ['task_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_tasks_user_status_created'), 'tasks', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_summaries_task_type'), 'summaries', ['task_id', 'summary_type', 'is_active'], unique=False)
    op.drop_column('summaries', 'comparison_id')
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('provider', 'provider_account_id', name=op.f('uk_accounts_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_accounts_user'), 'accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###
